apiVersion: v1
kind: Namespace
metadata:
  name: personal

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: iplookup
  namespace: personal
spec:
  selector:
    matchLabels:
      app: iplookup
  replicas: 1
  template:
    metadata:
      labels:
        app: iplookup
    spec:
      containers:
      - name: iplookup
        image: raphy02/iplookup:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: 80

---

apiVersion: v1
kind: Service
metadata:
  name: iplookup
  namespace: personal
  annotations:
    metallb.universe.tf/address-pool: production-public-ips
spec:
  selector:
    app: iplookup
  ports:
  - port: 80
    targetPort: 80

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: iplookup
  namespace: personal
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  tls:
  - hosts:
    - ip.raphaelbernhart.at
    secretName: ip-raphaelbernhart-at-tls
  rules:
  - host: ip.raphaelbernhart.at
    http:
      paths:
      - path: /
        backend:
          serviceName: iplookup
          servicePort: 80